
### calibration settings ###
start: '1980-10-01'
stop: '2019-12-31'

params_to_cal: ['ss_tau', 'gw_tau'] # parameters we want to calibrate

sntemp_output: ['seg_tave_air', 'seg_rain', 'seg_tave_water', 'seg_outflow', 'seg_tave_gw', 'seg_tave_sroff', 'seg_tave_ss',
'seg_tave_upstream', 'seg_upstream_inflow', 'seginc_gwflow', 'seginc_potet', 'seginc_sroff', 'seginc_ssflow',
'seginc_swrad', 'seg_humid', 'seg_shade', 'seg_ccov', 'seg_width']


