
### calibration settings ###
start: '2014-05-01'
stop: '2014-07-10'

params_to_cal: ['ss_tau', 'gw_tau'] # parameters we want to calibrate

param_ranges:
  param:
  - ss_tau
  - gw_tau
  min:
  - 1.0
  - 1.0
  max:
  - 200.0
  - 400.0

sntemp_output: ['seg_tave_air', 'seg_rain', 'seg_tave_water', 'seg_outflow', 'seg_tave_gw', 'seg_tave_sroff', 'seg_tave_ss',
'seg_tave_upstream', 'seg_upstream_inflow', 'seginc_gwflow', 'seginc_potet', 'seginc_sroff', 'seginc_ssflow',
'seginc_swrad', 'seg_humid', 'seg_shade', 'seg_ccov', 'seg_width']


